version: "3.8"

services:
  laravel:
    image: php:8.2-fpm
    container_name: laravel_app
    volumes:
      - ./laravel-app:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network
    depends_on:
      - mysql
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=python_laravel
      - DB_USERNAME=root
      - DB_PASSWORD=
    ports:
      - "8000:80"
  python:
    build:
      context: ./python-app
      dockerfile: Dockerfile
    container_name: python_app
    volumes:
      - ./python-app:/usr/src/app
    ports:
      - "5000:5000" # Map host port 5000 to container port 5000
    networks:
      - app-network
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=python_laravel
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
